GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/63bd1f39e37dbaf6c74f807b

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name" : "Amazing Person",
    "subscribedToChannel" : "Web Deb Simplified"
}

###
DELETE http://localhost:3000/subscribers/63bd1733050400ac8d04f983

###
PATCH  http://localhost:3000/subscribers/3bd1f39e37dbaf6c74f807b
Content-Type: application/json

{
    "name": "New Name"
}